# Generated by Django 5.1.7 on 2025-04-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='children',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
